SunglassesApp/Models/Promotion.cs
using System.ComponentModel.DataAnnotations;

namespace SunglassesApp.Models
{
    public class Promotion
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;
        public int? DiscountPercentage { get; set; }


        [DataType(DataType.Date)]
        public DateTime? StartDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        public ICollection<Product> Products { get; set; }  = new List<Product>();
    }

}

SunglassesApp/ViewModels/PromotionViewModel.cs
using SunglassesApp.Models;
using System.ComponentModel.DataAnnotations;

namespace SunglassesApp.ViewModels
{
    public class PromotionViewModel
    {
        public int Id { get; set; }
        public bool IsEdit { get; set; } = false;

        [Display(Name = "Naziv promocije")]
        [Required(ErrorMessage = "Unesite naziv promocije")]
        [StringLength(30, MinimumLength = 5, ErrorMessage = "Naziv promocije ne sme biti kraći od 5 i duži od 30 karaktera")]
        public string Name { get; set; } = null!;

        [Display(Name = "Procenat akcije")]
        [Required(ErrorMessage = "Unesite procenat akcije")]
        [Range(10,100, ErrorMessage = "Procenat akcije mora biti izmedju 10% i 100%")]
        public int? DiscountPercentage { get; set; }

        [Display(Name = "Početak promocije")]
        [Required(ErrorMessage = "Početni datum je obavezan")]
        [DataType(DataType.Date)]
        public DateTime? StartDate { get; set; }

        [Display(Name = "Kraj promocije")]
        [Required(ErrorMessage = "Krajnji datum je obavezan")]
        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

  
    }
}

SunglassesApp/Areas/Admin/Controllers/PromotionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using SunglassesApp.Data.Repositories.Implementations;
using SunglassesApp.Data.Repositories.Interfaces;
using SunglassesApp.Helpers;
using SunglassesApp.Models;
using SunglassesApp.ViewModels;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace SunglassesApp.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PromotionController : Controller
    {
        private readonly IPromotionRepository _promotionRepository;
        private readonly IProductRepository _productRepository;
        private ILogger<PromotionController> _logger;
        public PromotionController(IPromotionRepository promotionRepository, ILogger<PromotionController> logger, IProductRepository productRepository)
        {
            _promotionRepository = promotionRepository;
            _logger = logger;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> Index(string sortOrder, int page = 1)
        {
            int pageSize = 10;

            var promotions = _promotionRepository.GetAll();

            

            promotions = sortOrder switch
            {
                "discount_desc" => promotions.OrderByDescending(p => p.DiscountPercentage),
                "discount_asc" => promotions.OrderBy(p => p.DiscountPercentage),
                "default" => promotions.OrderByDescending(p => p.Id),
                _ => promotions.OrderBy(p => p.Id),
            };

            ViewBag.CurrentSort = sortOrder;
  
            var paginatedPromotions = await PaginatedList<Promotion>.CreateAsync(promotions, page, pageSize);

            return View("ManagePromotions", paginatedPromotions);
        }

        [HttpGet]
        public IActionResult PromotionForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPromotion(PromotionViewModel model)
        {
            ModelState.Remove("Id");

            if(!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Uneti podaci nisu validni";
                Helper.LogModelErrors(ModelState, _logger, "Uneti podaci nisu validni");

                return View("PromotionForm", model);
            }

            var newPromo = new Promotion
            {
                Name = model.Name,
                DiscountPercentage = model.DiscountPercentage,
                StartDate = model.StartDate,
                EndDate = model.EndDate,
            };

            try
            {
               await _promotionRepository.Insert(newPromo);
               await _promotionRepository.Save();
               TempData["SuccessMessage"] = "Uspešno dodavanje promocije";
            } 
            catch(Exception ex)
            {
                _logger.LogError("Greška: " + ex);
                TempData["ErrorMessage"] = "Došlo je do greške prilkom dodavanja promocije";
            }
            
            return View("PromotionForm", model);

        }

        [HttpPost]
        public async Task<IActionResult> DeletePromotion(int id)
        {
            try
            {
;               await _productRepository.ClearPromotions(id);

                await _promotionRepository.Delete(id);
                await _promotionRepository.Save();
                TempData["SuccessMessage"] = "Promocija je uspešno obrisana";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                _logger.LogError("Greška: " + ex);
                TempData["ErrorMessage"] = "Došlo je do greške prilikom brisanja promocije";
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public async Task<IActionResult> EditPromotion(int id)
        {
            var promotion = await _promotionRepository.Get(id);

            if(promotion == null)
            {
                TempData["ErrorMessage"] = "Promocija nije pronadjena";
                return View("Index");
            }

            var updatedPromotion = new PromotionViewModel
            {
                Name = promotion.Name,
                DiscountPercentage = promotion.DiscountPercentage,
                StartDate = promotion.StartDate,
                EndDate = promotion.EndDate,
                IsEdit = true
            };

            _logger.LogInformation("Pocetni datum: " + updatedPromotion.StartDate);

            return View("PromotionForm", updatedPromotion);
        }

        [HttpPost]
        public async Task<IActionResult> SavePromotion(PromotionViewModel viewModel)
        {

            if(!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Uneti podaci nisu validni";
                Helper.LogModelErrors(ModelState, _logger, "Uneti podaci nisu validni");
                return RedirectToAction("EditPromotion", viewModel);
            }

            var updatedPromotion = new Promotion
            {
                Id = viewModel.Id,
                Name = viewModel.Name,
                DiscountPercentage = viewModel.DiscountPercentage,
                StartDate = viewModel.StartDate,
                EndDate = viewModel.EndDate,
            };

            try
            {
                await _promotionRepository.Update(updatedPromotion);
                await _promotionRepository.Save();

                TempData["SuccessMessage"] = "Promocija je uspešno ažurirana";
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                _logger.LogError("Greška: " + ex);
                TempData["ErrorMessage"] = "Došlo je do greške prilikom ažuriranja promocije\nPokušajte ponovo...";
                return RedirectToAction("EditPromotion", viewModel);
            }
        }


    }
}

SunglassesApp/Areas/Admin/Views/Promotion/ManagePromotions.cshtml
@using SunglassesApp.Helpers
@using SunglassesApp.Models

@{
    Layout = "_AdminLayout";
}

@model PaginatedList<Promotion>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h1>Proizvodi</h1>

<div class="container">
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger mt-3 alert-dismissible fade show" role="alert">
            @TempData["ErrorMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="card mt-4 bg-gray">
        
        <div class="card-header  text-center text-light bg-gray d-flex flex-row-reverse justify-content-between flex-wrap align-items-center">
            <form method="get" asp-controller="Promotion" asp-action="Index" class="d-flex justify-content-end">
                <select name="sortOrder" class="form-select" onchange="this.form.submit()">
                    <option value="default" selected="@(ViewBag.CurrentSort == null || ViewBag.CurrentSort == "default")">Podrazumevano</option>
                    <option value="discount_asc" selected="@(ViewBag.CurrentSort == "discount_asc")">Rastuće</option>
                    <option value="discount_desc" selected="@(ViewBag.CurrentSort == "discount_desc")">Opadajuće</option>
                </select>
            </form>
            <h5 class="mb-0"><i class="fas fa-trophy me-2"></i>Dostupne promocije</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive  border-top rounded-top">
                <table class="table table-hover table-secondary ">
                    <thead class="table-dark text-light">
                        <tr>
                            <th>Naziv promocije</th>
                            <th>Akcija</th>
                            <th>Početak</th>
                            <th>Kraj</th>
                            <th>Izmeni</th>
                            <th>Obriši</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var p in Model)
                        {
                            <tr>
                                <td>@p.Name</td>
                                <td>@p.DiscountPercentage%</td>
                                <td>@p.StartDate?.ToString("dd.MM.yyyy")</td>
                                <td>@p.EndDate?.ToString("dd.MM.yyyy")</td>
                                
                                <td>
                                    <form asp-action="EditPromotion" asp-controller="Promotion" asp-route-id="@p.Id" method="get" class="d-inline">
                                        <button type="submit" class="border-0 bg-transparent p-0">
                                            <i class="bi bi-pencil text-success fw-bolder p-2 " style="font-size: 1.2rem"></i>
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <form asp-action="DeletePromotion" asp-controller="Promotion" asp-area="Admin" asp-route-id="@p.Id" method="post" class="d-inline">
                                        <button type="submit" class="border-0 bg-transparent p-0">
                                            <i class="bi bi-trash text-danger fw-bolder p-2" style="font-size: 1.2rem"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
                @if (Model is PaginatedList<Promotion> paged && paged.TotalPages > 0)
                {
                    <nav aria-label="Product pagination">
                        <ul class="pagination justify-content-center mt-4">
                            <li class="page-item @(paged.HasPreviousPage ? "" : "disabled")">
                                <form method="get" asp-controller="Customer" asp-action="Index" class="d-inline">

                                    <input type="hidden" name="sortOrder" value="@ViewBag.CurrentSort" />
                                    <input type="hidden" name="page" value="@(paged.PageIndex - 1)" />
                                    <button class="page-link" type="submit" aria-label="Prethodna" tabindex="-1">&laquo;</button>
                                </form>
                            </li>
                            @for (int i = 1; i <= paged.TotalPages; i++)
                            {
                                <li class="page-item @(i == paged.PageIndex ? "active" : "")">
                                    <form method="get" asp-controller="Customer" asp-action="Index" class="d-inline">

                                        <input type="hidden" name="sortOrder" value="@ViewBag.CurrentSort" />
                                        <input type="hidden" name="page" value="@i" />
                                        <button class="page-link" type="submit">@i</button>
                                    </form>
                                </li>
                            }
                            <li class="page-item @(paged.HasNextPage ? "" : "disabled")">
                                <form method="get" asp-controller="Customer" asp-action="Index" class="d-inline">

                                    <input type="hidden" name="sortOrder" value="@ViewBag.CurrentSort" />
                                    <input type="hidden" name="page" value="@(paged.PageIndex + 1)" />
                                    <button class="page-link" type="submit" aria-label="Sledeća">&raquo;</button>
                                </form>
                            </li>
                        </ul>
                    </nav>
                }
            </div>

        </div>

        

    </div>


</div>

SunglassesApp/Areas/Admin/Views/Promotion/PromotionForm.cshtml
@using SunglassesApp.ViewModels
@model PromotionViewModel;
@{
    Layout = "_AdminLayout";
    bool isEdit = false;
    if(Model != null)
    {
        isEdit = Model.IsEdit;
    }

    string header = isEdit ? "Izmena promocije" : "Dodaj promociju";
}




<div class="container-md">
    @using (Html.BeginForm(isEdit ? "SavePromotion" : "AddPromotion", "Promotion", FormMethod.Post, new
    {
        @class = "needs-validation dark-gradient rounded-3 p-5 shadow",
        novalidate = "novalidate"
    }))
    {
        <h1>@header</h1>
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id);
      

        <div class="form-group-wrapper">
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "form-label text-light" })
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control bg-secondary text-light shadow" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DiscountPercentage, new { @class = "form-label text-light" })
                @Html.TextBoxFor(m => m.DiscountPercentage, new {
                        @class = "form-control bg-secondary text-light shadow",
                        type = "number",
                        min = "10",
                        max = "100",
                      
                })
                @Html.ValidationMessageFor(m => m.DiscountPercentage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group-wrapper">
            <div class="form-group">
                @Html.LabelFor(m => m.StartDate,  new { @class = "form-label text-light" })
                @Html.TextBoxFor(m => m.StartDate, "{0:yyyy-MM-dd}", new {
                    @class = "form-control bg-secondary text-light shadow",
                    type = "date"
                })
                @Html.ValidationMessageFor(m => m.StartDate, "", new { @class = "text-danger" })
            </div>
           
        </div>

        <div class="form-group-wrapper">
            <div class="form-group">
                @Html.LabelFor(m => m.EndDate,  new { @class = "form-label text-light" })
            @Html.TextBoxFor(m => m.EndDate,"{0:yyyy-MM-dd}", new {
                        @class = "form-control bg-secondary text-light shadow",
                    type = "date",
                     
                })
                @Html.ValidationMessageFor(m => m.EndDate, "", new { @class = "text-danger" })
            </div>

        </div>
    <div class="d-flex justify-content-center pt-4">
        <button type="submit" class="btn btn-success shadow">Sačuvaj</button>
    </div>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
            @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger mt-3">
            @TempData["ErrorMessage"]
        </div>
    }

    }
</div>