SunglassesApp/ViewModels/RecommendationViewModel.cs
using SunglassesApp.Models;

namespace SunglassesApp.ViewModels
{
    public class RecommendationViewModel
    {
        public List<Message> Messages { get; set; } = new List<Message>();
        public Message? Message { get; set; } 
        public int ProductId { get; set; }
    }
}

SunglassesApp/Controllers/RecommendationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SunglassesApp.Data.Repositories.Interfaces;
using SunglassesApp.Models;
using SunglassesApp.ViewModels;
using System.Threading.Tasks;

namespace SunglassesApp.Controllers
{
    [Authorize(Roles = "User")]
    public class RecommendationController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private ILogger<RecommendationController> _logger;
        private IMessageRepository _messageRepository;
        private IUserRepository _userRepository;
        
        public RecommendationController
            (
            UserManager<ApplicationUser> userManager,
            ILogger<RecommendationController> logger,
            IMessageRepository messageRepository,
            IUserRepository userRepository
            )
        {
             _userManager = userManager;
            _logger = logger;
            _messageRepository = messageRepository;
            _userRepository = userRepository;
        }

        private async Task<ApplicationUser> GetUser()
        {
            var user = await _userManager.GetUserAsync(User);
            return user!;
        }

        private string GetUserId()
        {
            return _userManager.GetUserId(User)!;
        }

        public async Task<IActionResult> Index()
        {

            var messages = await _messageRepository.GetAllUserMessages(GetUserId()).ToListAsync();

            return View(messages);
        }

        public async Task<IActionResult> Recommend(ProductDetailsViewModel vm, int productId, string brand, string model)
        {
            string userName = vm.UserName;
            var user = await GetUser();
            var userId = GetUserId();

            try
            {
                var reciever = await _userRepository.GetUserByUserName(userName);
                if(reciever == null)
                {
                    TempData["ErrorMessage"] = "Traženi korisnik nije pronadjen";
                    
                    return RedirectToAction("ProductDetails", "Customer", new { id = productId});
                }
                if(reciever.UserName == user.UserName)
                {
                    TempData["ErrorMessage"] = "Slanje preporuke sebi nije moguće";

                    return RedirectToAction("ProductDetails", "Customer", new { id = productId });
                }

                var message = new Message
                {
                    SenderId = userId,
                    RecieverId = reciever.Id,
                    MessageContent = $"{user.UserName} vam preporučuje proizvod: {brand} {model}",
                    ProductId = productId,
                };



                await _messageRepository.AddMessage(message);
                await _messageRepository.Save();

                TempData["SuccessMessage"] = "Preporuka je uspešno poslata";
                return RedirectToAction("ProductDetails", "Customer", new { id = productId });

            }
            catch (Exception ex)
            {
                _logger.LogError("GREŠKA! " + ex);
                TempData["ErrorMessage"] = "Došlo je do greške... Pokušajte ponovo kasnije";
                return BadRequest();

            }

        }

        public async Task<IActionResult> ClearMessages()
        {

            try
            {
                await _messageRepository.DeleteAllMessages(GetUserId());
                await _messageRepository.Save();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                _logger.LogError("GREŠKA! " + ex);
                TempData["ErrorMessage"] = "Došlo je do greške prilikom brisanja preporuka... Pokušajte ponovo kasnije";
                return RedirectToAction("Index");
            }
        }

    }
}

SunglassesApp/Views/Recommendation/Index.cshtml
@using SunglassesApp.Models;
@using SunglassesApp.Helpers;
@using SunglassesApp.ViewModels
@model IEnumerable<Message>;
@{
    Layout = "_Layout";
}


<div class="container my-5 bg-light shadow rounded-3 pb-1 w-75">
    <div class="w-100 d-flex justify-content-between p-2">
        <h2 class="mb-4 pt-2">📩 Moje preporuke</h2>
        @if (Model.Any())
        {
            <form asp-controller="Recommendation" asp-action="ClearMessages">
                <button type="submit" class="btn btn-danger p-1 h-50 mt-3 shadow">Obriši preporuke</button>
            </form>
        }
    </div>
    @if (!Model.Any())
    {
        <div class="alert alert-info">
            Trenutno nemate nijednu preporuku
        </div>
    }
    else
    {
        <table class="table table-hover shadow-sm">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>

                    <th scope="col">Poruka<meta name="viewport" content="width=device-width" /></th>
                 
                    <th scope="col">Datum dospeća</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var r in Model)
                {
                    <tr onclick="window.location.href='@Url.Action("ProductDetails", "Customer", new { id = r.ProductId })'" style="cursor:pointer;">
                        <th scope="row">@r.Id</th>
                        <td>@r.MessageContent</td>
                        
                        <td>@r.SentAt.ToString("dd.MM.yyyy")</td>
                    </tr>
                }
            </tbody>
        </table>

    }
</div>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success text-center fixed-top alert-dismissible mt-3 fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger text-center fixed-top alert-dismissible mt-3 fade show">
        @TempData["ErrorMessage"]
    </div>
}